/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations
  }
  collections: {
    journals: Journal
    'onboarding-form-submissions': OnboardingFormSubmission
    'onboarding-step-values': OnboardingStepValue
    users: User
    'payload-locked-documents': PayloadLockedDocument
    'payload-preferences': PayloadPreference
    'payload-migrations': PayloadMigration
  }
  collectionsJoins: {
    users: {
      journalNotes: 'journals'
      onboardingForm: 'onboarding-form-submissions'
    }
  }
  collectionsSelect: {
    journals: JournalsSelect<false> | JournalsSelect<true>
    'onboarding-form-submissions': OnboardingFormSubmissionsSelect<false> | OnboardingFormSubmissionsSelect<true>
    'onboarding-step-values': OnboardingStepValuesSelect<false> | OnboardingStepValuesSelect<true>
    users: UsersSelect<false> | UsersSelect<true>
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>
  }
  db: {
    defaultIDType: number
  }
  globals: {
    onboarding: Onboarding
  }
  globalsSelect: {
    onboarding: OnboardingSelect<false> | OnboardingSelect<true>
  }
  locale: 'uk' | 'en'
  user: User & {
    collection: 'users'
  }
  jobs: {
    tasks: unknown
    workflows: unknown
  }
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string
    password: string
  }
  login: {
    email: string
    password: string
  }
  registerFirstUser: {
    email: string
    password: string
  }
  unlock: {
    email: string
    password: string
  }
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals".
 */
export interface Journal {
  id: number
  title?: string | null
  content?: string | null
  user: number | User
  type?: ('journal' | 'mood-tracker') | null
  mood?: ('happy' | 'sad' | 'angry' | 'anxious' | 'neutral') | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number
  firstName: string
  roles: ('root' | 'user')[]
  journalNotes?: {
    docs?: (number | Journal)[] | null
    hasNextPage?: boolean | null
  } | null
  signUpFlowCompleted?: boolean | null
  onboardingCompleted?: boolean | null
  onboardingStep?: ('userGoals' | 'initialEmotionalState' | 'wantedFeatures' | 'personalizedAINotificationsPermission') | null
  onboardingForm?: {
    docs?: (number | OnboardingFormSubmission)[] | null
    hasNextPage?: boolean | null
  } | null
  sub?: string | null
  updatedAt: string
  createdAt: string
  email: string
  resetPasswordToken?: string | null
  resetPasswordExpiration?: string | null
  salt?: string | null
  hash?: string | null
  loginAttempts?: number | null
  lockUntil?: string | null
  password?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-form-submissions".
 */
export interface OnboardingFormSubmission {
  id: number
  user: number | User
  userGoals?: (number | OnboardingStepValue)[] | null
  initialEmotionalState?: (number | OnboardingStepValue)[] | null
  wantedFeatures?: (number | OnboardingStepValue)[] | null
  personalizedAINotificationsPermission?: boolean | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-step-values".
 */
export interface OnboardingStepValue {
  id: number
  step: 'userGoals' | 'initialEmotionalState' | 'wantedFeatures'
  value: string
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number
  document?:
    | ({
        relationTo: 'journals'
        value: number | Journal
      } | null)
    | ({
        relationTo: 'onboarding-form-submissions'
        value: number | OnboardingFormSubmission
      } | null)
    | ({
        relationTo: 'onboarding-step-values'
        value: number | OnboardingStepValue
      } | null)
    | ({
        relationTo: 'users'
        value: number | User
      } | null)
  globalSlug?: string | null
  user: {
    relationTo: 'users'
    value: number | User
  }
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number
  user: {
    relationTo: 'users'
    value: number | User
  }
  key?: string | null
  value?:
    | {
        [k: string]: unknown
      }
    | unknown[]
    | string
    | number
    | boolean
    | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number
  name?: string | null
  batch?: number | null
  updatedAt: string
  createdAt: string
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journals_select".
 */
export interface JournalsSelect<T extends boolean = true> {
  title?: T
  content?: T
  user?: T
  type?: T
  mood?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-form-submissions_select".
 */
export interface OnboardingFormSubmissionsSelect<T extends boolean = true> {
  user?: T
  userGoals?: T
  initialEmotionalState?: T
  wantedFeatures?: T
  personalizedAINotificationsPermission?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding-step-values_select".
 */
export interface OnboardingStepValuesSelect<T extends boolean = true> {
  step?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T
  roles?: T
  journalNotes?: T
  signUpFlowCompleted?: T
  onboardingCompleted?: T
  onboardingStep?: T
  onboardingForm?: T
  sub?: T
  updatedAt?: T
  createdAt?: T
  email?: T
  resetPasswordToken?: T
  resetPasswordExpiration?: T
  salt?: T
  hash?: T
  loginAttempts?: T
  lockUntil?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T
  globalSlug?: T
  user?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T
  key?: T
  value?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T
  batch?: T
  updatedAt?: T
  createdAt?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding".
 */
export interface Onboarding {
  id: number
  steps: {
    userGoals: {
      type: 'multipleChoiceList' | 'multipleChoiceChips'
      data?: (number | OnboardingStepValue)[] | null
    }
    initialEmotionalState: {
      type: 'multipleChoiceList' | 'multipleChoiceChips'
      data?: (number | OnboardingStepValue)[] | null
    }
    wantedFeatures: {
      type: 'multipleChoiceList' | 'multipleChoiceChips'
      data?: (number | OnboardingStepValue)[] | null
    }
  }
  updatedAt?: string | null
  createdAt?: string | null
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding_select".
 */
export interface OnboardingSelect<T extends boolean = true> {
  steps?:
    | T
    | {
        userGoals?:
          | T
          | {
              type?: T
              data?: T
            }
        initialEmotionalState?:
          | T
          | {
              type?: T
              data?: T
            }
        wantedFeatures?:
          | T
          | {
              type?: T
              data?: T
            }
      }
  updatedAt?: T
  createdAt?: T
  globalType?: T
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
