export enum EmotionsValues {
  Happy = 'happy',
  Sad = 'sad',
  Angry = 'angry',
  Mad = 'mad',
  Scared = 'scared',
  Peaceful = 'peaceful',
  Hateful = 'hateful',
  Hopeful = 'hopeful',
  Sleepy = 'sleepy',
  Excited = 'excited',
  Calm = 'calm',
  Frustrated = 'frustrated',
  Lonely = 'lonely',
  Grateful = 'grateful',
  Confused = 'confused',
}
