packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@commitlint/config-conventional': ^19.6.0
  '@commitlint/config-pnpm-scopes': ^19.5.0
  '@headlessui/tailwindcss': ^0.2.1
  '@inlang/paraglide-sveltekit': ^0.15.5
  '@inlang/paraglide-js': ^1.11.8
  '@next/env': ^15.1.6
  '@payloadcms/db-sqlite': ^3.19.0
  '@payloadcms/email-nodemailer': ^3.19.0
  '@payloadcms/next': ^3.19.0
  '@payloadcms/plugin-multi-tenant': ^3.19.0
  '@payloadcms/plugin-nested-docs': ^3.19.0
  '@payloadcms/plugin-redirects': ^3.19.0
  '@payloadcms/plugin-seo': ^3.19.0
  '@payloadcms/richtext-lexical': ^3.19.0
  '@payloadcms/storage-s3': ^3.19.0
  '@payloadcms/translations': ^3.19.0
  '@payloadcms/ui': ^3.19.0
  '@sveltejs/adapter-cloudflare': ^5.0.1
  '@sveltejs/kit': ^2.16.1
  '@sveltejs/package': ^2.3.9
  '@sveltejs/vite-plugin-svelte': ^5.0.3
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/vite': ^4.0.0
  '@turbo/gen': ^2.3.4
  '@types/eslint': ^9.6.1
  '@types/node': ^22.10.10
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  '@vite-pwa/assets-generator': ^0.2.6
  '@vite-pwa/sveltekit': ^0.6.7
  '@zapal/dx': ^1.2.0
  '@zapal/payload-email-sendgrid': ^1.0.6
  dotenv: ^16.4.7
  dotenv-expand: ^12.0.1
  eslint: ^9.18.0
  husky: ^9.1.7
  next: ^15.1.6
  payload: ^3.19.0
  payload-oauth2: ^1.0.9
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.0.0
  'react-dom': ^19.0.0
  sharp: ^0.33.5
  svelte: ^5.19.2
  svelte-check: ^4.1.4
  svelte-headlessui: ^0.0.46
  tailwindcss: ^4.0.0
  turbo: ^2.3.4
  typescript: ^5.7.3
  vite: ^6.0.11
